name: Build OpenCV.js

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libv4l-dev

      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.13.1
        with:
          cmake-version: 3.28

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: opencv-js

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Get version
        id: get_version
        working-directory: opencv-js
        run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Checkout OpenCV
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv
          ref: refs/tags/${{ steps.get_version.outputs.VERSION }}
          path: 'opencv'

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          actions-cache-folder: emsdk-cache

      - name: Verify Emscripten
        run: emcc -v

      - name: Build opencv.js
        working-directory: opencv
        run: |
          mkdir -p build_wasm
          cd build_wasm

          emcmake cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_opencv_js=ON \
            -DBUILD_LIST=core,imgproc,highgui \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTS=OFF \
            -DBUILD_PERF_TESTS=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DCMAKE_INSTALL_PREFIX="$PWD/install" \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DEMSCRIPTEN_LINKER_FLAGS="-s WASM=1" \
            ..

          emmake make -j"$(nproc)" opencv.js
          emmake make install

      - name: List build outputs
        run: |
          ls -la opencv/build_wasm/bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: opencv.js
          path: opencv/build_wasm/bin
          if-no-files-found: error
